version: "3.9"
services: 
  postgres:
    image: postgres:12-alpine
    environment: 
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=todoapp
      - POSTGRES_USER=root
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    environment: 
      - DB_SOURCE=postgresql://root:secret@postgres:5432/todoapp?sslmode=disable
    depends_on: 
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
