// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Todo struct {
	ID          uuid.UUID
	Title       string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
